### ISSUE TITLE
[Bug] [Infrastructure] combineremediations.py helper fails to build correctly on 32-bit (i686) python-2.7.5 version

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1332]
There's this Python-2.7.5 issue affecting the 32-bit architecture:
[1]  https://bugs.python.org/issue17998

corrected in Python upstream with the following patch for 2.7.X version:
[2]  https://hg.python.org/cpython/rev/e5e425fd1e4f

This issue also exhibits in `combineremediations.py` helper, when scap-security-guide build is attempted on python-2.7.5 version (currently in Red Hat Enterprise Linux 7) with 32-bit (i686) python RPM packages installed. More detailed error message:

```
...
oscap xccdf resolve -o output/xccdf-unlinked-resolved.xml output/xccdf-unlinked-empty-groups-unselected.xml
xsltproc -o output/ocil-unlinked.xml ../../shared/transforms/xccdf-create-ocil.xslt output/xccdf-unlinked-resolved.xml
xmllint --format --output output/unlinked-rhel7-ocil.xml output/ocil-unlinked.xml
xsltproc -stringparam product "rhel7" -o output/xccdf-unlinked-ocilrefs.xml ../../shared/transforms/xccdf-ocilcheck2ref.xslt output/xccdf-unlinked-resolved.xml
# Make intermediate build/remediations directory to hold final list of remediation scripts for rhel7
mkdir -p build/remediations
# Search ../../shared/remediations/bash and input/remediations directories to find all product specific remediation scripts,
# which are regular files (not symlinks). Merge the final list into build/remediations directory
find ../../shared/remediations/bash input/remediations/bash -maxdepth 1 -type f -name '*.sh' -exec cp {} build/remediations ';'
../../shared/transforms/combineremediations.py rhel7 build/remediations output/bash-remediations.xml
Traceback (most recent call last):
  File "../../shared/transforms/combineremediations.py", line 309, in <module>
    main()
  File "../../shared/transforms/combineremediations.py", line 297, in main
    expand_xccdf_subs(fix, remediation_functions)
  File "../../shared/transforms/combineremediations.py", line 151, in expand_xccdf_subs
    _, head, tail, _ = re.split(rfpatcomp, fixparts[0], maxsplit=2)
  File "/usr/lib/python2.7/re.py", line 167, in split
    return _compile(pattern, flags).split(string, maxsplit)
RuntimeError: internal error in regular expression engine
make: *** [output/bash-remediations.xml] Error 1
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.BlyIVX (%build)
    Bad exit status from /var/tmp/rpm-tmp.BlyIVX (%build)
Child returncode was: 1
...
```

The following python RPM was installed on that system: `python-libs.i686 0:2.7.5-34.el7`

Since it seems python version in Red Hat Enterprise Linux 7 doesn't contain upstream [2] fix yet, we should provide a SSG workaround for regex (make a shorter regex so the issue [1] wouldn't exhibit) in:

```
  File "../../shared/transforms/combineremediations.py", line 151, in expand_xccdf_subs
    _, head, tail, _ = re.split(rfpatcomp, fixparts[0], maxsplit=2)
```

Preliminary targeting for 0.1.31 release.

**Comment by redhatrises** [comment]
Just tried this with `python-libs.i686 0:2.7.5-48.el7` installed, and I can't reproduce the error. Closing the ticket. We can re-open if necessary.
