### ISSUE TITLE
Python script that checks SVG support is breaking

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/scap-security-guide#1705]
On a RHEL7 system:

```
# ./shared/utils/oscap-svg-support.py ;echo $?
Traceback (most recent call last):
  File "./shared/utils/oscap-svg-support.py", line 42, in <module>
    child = Popen(command.split(), stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
1
```

This issue revealed a bug fixed in #1704.

**Comment by redhatrises** [comment]
@yuumasato tired this out using `./shared/utils/oscap-svg-support.py ;echo $?`, and I am not getting this error. Can you confirm?

**Comment by yuumasato** [comment]
I don't get this error anymore.
