### ISSUE TITLE
Ubuntu build fails with CMake

### ISSUE THREAD

**Issue by pthierry38** [OpenSCAP/scap-security-guide#1720]
Hi everyone. Since the update to cmake, I don't manage to build any of the targets. I have the same error for each:

```shell
scap-security-guide/build$ make
[  0%] Built target chromium-tables
[  0%] Built target generate-internal-chromium-guide.xml
[  0%] Built target generate-internal-chromium-shorthand.xml
[  1%] Built target generate-internal-chromium-xccdf-unlinked-resolved.xml
[  1%] Built target generate-internal-chromium-puppet-remediations.xml
[  1%] Built target generate-internal-chromium-bash-remediations.xml
[  1%] Built target generate-internal-chromium-ansible-remediations.xml
[  1%] Built target generate-internal-chromium-anaconda-remediations.xml
[  1%] Built target generate-internal-chromium-ocil-unlinked.xml
[  1%] Built target generate-internal-chromium-xccdf-unlinked-ocilrefs.xml
[  1%] Built target generate-internal-chromium-xccdf-unlinked.xml
[  1%] Built target generate-internal-chromium-oval-unlinked.xml
[  1%] Built target generate-internal-chromium-linked-xccdf-oval-ocil.xml
[  2%] Built target generate-ssg-chromium-xccdf.xml
[  4%] Built target generate-ssg-chromium-oval.xml
[  4%] Built target generate-ssg-chromium-ocil.xml
[  4%] Built target generate-ssg-chromium-cpe-dictionary.xml
[  4%] Built target generate-ssg-chromium-xccdf-1.2.xml
[  4%] [chromium] generating ssg-chromium-ds.xml
OpenSCAP Error: Unknown document type: 'ssg-chromium-ocil.xml' [../../../src/source/oscap_source.c:172]
Traceback (most recent call last):
  File "../../shared/utils/sds-move-ocil-to-checks.py", line 205, in <module>
    main()
  File "../../shared/utils/sds-move-ocil-to-checks.py", line 194, in main
    move_ocil_content_from_ds_extended_component_to_ds_component(datastreamtree, oldocilhref)
  File "../../shared/utils/sds-move-ocil-to-checks.py", line 122, in move_ocil_content_from_ds_extended_component_to_ds_component
    extcomptree = ET.fromstring(extnohtmlents)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: XML declaration allowed only at the start of the document, line 2, column 41
Chromium/CMakeFiles/generate-ssg-chromium-ds.xml.dir/build.make:65: recipe for target 'ssg-chromium-ds.xml' failed
make[2]: *** [ssg-chromium-ds.xml] Error 1
make[2]: *** Deleting file 'ssg-chromium-ds.xml'
CMakeFiles/Makefile2:1197: recipe for target 'Chromium/CMakeFiles/generate-ssg-chromium-ds.xml.dir/all' failed
make[1]: *** [Chromium/CMakeFiles/generate-ssg-chromium-ds.xml.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

scap-security-guide/build$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

Is it possible to add an Ubuntu template  to the list of the distros used by jenkins tests ? I think only one would be enough to detect most of the problems.

**Comment by mpreisler** [comment]
What's in the file?

**Comment by pthierry38** [comment]
The ocil file (build/ssg-chromium-ocil.xml) looks correct:
```xml
<?xml version="1.0"?>
<ocil xmlns="http://scap.nist.gov/schema/ocil/2.0">
  <generator>
    <schema_version>2.0</schema_version>
    <timestamp>2017-02-23T12:29:11+01:00</timestamp>
  </generator>
  <questionnaires>
    <questionnaire id="ocil:ssg-chromium_policy_file_ocil:questionnaire:1">
      <title>Ensure the Chromium Policy Configuration File Exists</title>
      <actions>
[...]
```
Same error for targets debian8, rhel7 on same line exactly.

**Comment by mpreisler** [comment]
There seems to be an empty line before the XML decl.

**Comment by pthierry38** [comment]
I can during next 2 hours

**Comment by pthierry38** [comment]
The ocil file doesn't look like having an empty line (i've also checked for invalid or unprintable char)
```
$ cat -e ssg-chromium-ocil.xml |head
<?xml version="1.0"?>$
<ocil xmlns="http://scap.nist.gov/schema/ocil/2.0">$
  <generator>$
    <schema_version>2.0</schema_version>$
    <timestamp>2017-02-23T12:29:11+01:00</timestamp>$
  </generator>$
  <questionnaires>$
    <questionnaire id="ocil:ssg-chromium_policy_file_ocil:questionnaire:1">$
      <title>Ensure the Chromium Policy Configuration File Exists</title>$
      <actions>$
```

**Comment by pthierry38** [comment]
here is the oscap version, if it can help:
```
$ oscap --version
OpenSCAP command line tool (oscap) 1.2.8
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/lib/x86_64-linux-gnu/openscap

==== Inbuilt CPE names ====

==== Supported OVAL objects and associated OpenSCAP probes ====
system_info                  probe_system_info           
family                       probe_family                
filehash                     probe_filehash              
environmentvariable          probe_environmentvariable   
textfilecontent54            probe_textfilecontent54     
textfilecontent              probe_textfilecontent       
variable                     probe_variable              
xmlfilecontent               probe_xmlfilecontent        
environmentvariable58        probe_environmentvariable58 
filehash58                   probe_filehash58            
dpkginfo                     probe_dpkginfo              
inetlisteningservers         probe_inetlisteningservers  
partition                    probe_partition             
iflisteners                  probe_iflisteners           
selinuxboolean               probe_selinuxboolean        
selinuxsecuritycontext       probe_selinuxsecuritycontext
file                         probe_file                  
interface                    probe_interface             
password                     probe_password              
process                      probe_process               
runlevel                     probe_runlevel              
shadow                       probe_shadow                
uname                        probe_uname                 
xinetd                       probe_xinetd                
sysctl                       probe_sysctl                
process58                    probe_process58             
fileextendedattribute        probe_fileextendedattribute 
routingtable                 probe_routingtable          
symlink                      probe_symlink
```

**Comment by pthierry38** [comment]
There is no ds:extended-component in the build/ dir (I've built (unsussessefully) debian8, chromium, rhel7)
```
$ grep -r "ds:extended-component" .
$
```
The impacted code (line 122, file sds-move-ocil-to-check.py) seems to manage this part.

**Comment by pthierry38** [comment]
The error is exactly here:
```
$ /usr/bin/oscap ds sds-compose /xxxx/scap-security-guide/build/ssg-debian8-xccdf-1.2.xml /xxxx/scap-security-guide/build/ssg-debian8-ds.xml
OpenSCAP Error: Unknown document type: 'ssg-debian8-ocil.xml' [../../../src/source/oscap_source.c:172]
```
Its before the call to the python script. Here is the content of the two files passed to oscap

$ cat -ve build/ssg-debian8-xccdf-1.2.xml |head
```xml
<?xml version="1.0"?>$
<Benchmark xmlns="http://checklists.nist.gov/xccdf/1.2" id="xccdf_org.ssgproject.content_benchmark_DEBIAN-8" resolved="1" xml:lang="en-US" style="SCAP_1.1">$
  <status date="2017-02-23">draft</status>$
  <title xml:lang="en-US">Guide to the Secure Configuration of Debian 8</title>$
  <description xml:lang="en-US">This guide presents a catalog of security-relevant$
configuration settings for Debian 8. It is a rendering of$
content structured in the eXtensible Configuration Checklist Description Format (XCCDF)$
in order to support security automation.  The SCAP content is$
is available in the <html:code xmlns:html="http://www.w3.org/1999/xhtml">scap-security-guide</html:code> package which is developed at$
<html:a xmlns:html="http://www.w3.org/1999/xhtml" href="https://www.open-scap.org/security-policies/scap-security-guide">https://www.open-scap.org/security-policies/scap-security-guide</html:a>.$
```

$ cat -ve /home/pret/git/scap/scap-security-guide/build/ssg-debian8-ds.xml |head
```xml
<?xml version="1.0" encoding="utf-8"?>$
<ds:data-stream-collection xmlns:ds="http://scap.nist.gov/schema/scap/source/1.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cat="urn:oasis:names:tc:entity:xmlns:xml:catalog" id="scap_org.open-scap_collection_from_xccdf_ssg-debian8-xccdf-1.2.xml" schematron-version="1.0"><ds:data-stream id="scap_org.open-scap_datastream_from_xccdf_ssg-debian8-xccdf-1.2.xml" scap-version="1.2" use-case="OTHER"><ds:checklists><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-xccdf-1.2.xml" xlink:href="#scap_org.open-scap_comp_ssg-debian8-xccdf-1.2.xml"><cat:catalog><cat:uri name="ssg-debian8-oval.xml" uri="#scap_org.open-scap_cref_ssg-debian8-oval.xml"/><cat:uri name="ssg-debian8-ocil.xml" uri="#scap_org.open-scap_cref_ssg-debian8-ocil.xml"/></cat:catalog></ds:component-ref></ds:checklists><ds:checks><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-oval.xml" xlink:href="#scap_org.open-scap_comp_ssg-debian8-oval.xml"/></ds:checks><ds:extended-components><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-ocil.xml" xlink:href="#scap_org.open-scap_ecomp_ssg-debian8-ocil.xml"/></ds:extended-components></ds:data-stream><ds:component id="scap_org.open-scap_comp_ssg-debian8-oval.xml" timestamp="2017-02-23T16:42:55"><oval_definitions xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:linux="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux" xmlns:unix="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix" xmlns:ind="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5 oval-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#independent independent-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#unix unix-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#linux linux-definitions-schema.xsd">$
  <generator>$
    <oval:product_name>python</oval:product_name>$
    <oval:product_version>2.7.12</oval:product_version>$
    <oval:schema_version>5.11</oval:schema_version>$
    <oval:timestamp>2017-02-23T15:42:50</oval:timestamp>$
  </generator>$
  <definitions>$
    <definition class="compliance" id="oval:ssg-rsyslog_files_ownership:def:1" version="1">$
```

**Comment by pthierry38** [comment]
It seems that there is an invalid href usage in the generated xccdf file (end of each line):
grep -r "ssg-debian8-ocil.xml" scap-security-guide/build/ssg-debian8-xccdf-1.2.xml 
```xml
              <check-content-ref name="ocil:ssg-file_permissions_systemmap_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_shadow_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_gshadow_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_passwd_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_group_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-sysctl_fs_suid_dumpable_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-sysctl_kernel_randomize_va_space_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-sysctl_kernel_kptr_restrict_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_tmp_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_var_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_var_log_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_var_log_audit_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_home_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-partition_for_srv_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sysctl_fs_protected_symlinks_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sysctl_fs_protected_hardlinks_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
          <check-content-ref name="ocil:ssg-package_rsyslog_installed_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
          <check-content-ref name="ocil:ssg-service_rsyslog_enabled_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-rsyslog_files_ownership_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-rsyslog_files_groupownership_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-rsyslog_files_permissions_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-rsyslog_remote_loghost_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-ensure_logrotate_activated_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
          <check-content-ref name="ocil:ssg-service_auditd_enabled_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
          <check-content-ref name="ocil:ssg-service_ntpd_enabled_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sshd_allow_only_protocol2_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sshd_set_idle_timeout_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sshd_set_keepalive_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sshd_disable_root_login_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
            <check-content-ref name="ocil:ssg-sshd_disable_empty_passwords_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/
```

**Comment by pthierry38** [comment]
In the generated ds also, but maybe it is due to the uri name="ssg-debian8-ocil.xml", which is maybe not supported (first line)
$ cat ../../ssg-debian8-ds.xml |grep "ssg-debian8-ocil.xml"
```xml
<ds:data-stream-collection xmlns:ds="http://scap.nist.gov/schema/scap/source/1.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cat="urn:oasis:names:tc:entity:xmlns:xml:catalog" id="scap_org.open-scap_collection_from_xccdf_ssg-debian8-xccdf-1.2.xml" schematron-version="1.0"><ds:data-stream id="scap_org.open-scap_datastream_from_xccdf_ssg-debian8-xccdf-1.2.xml" scap-version="1.2" use-case="OTHER"><ds:checklists><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-xccdf-1.2.xml" xlink:href="#scap_org.open-scap_comp_ssg-debian8-xccdf-1.2.xml"><cat:catalog><cat:uri name="ssg-debian8-oval.xml" uri="#scap_org.open-scap_cref_ssg-debian8-oval.xml"/><cat:uri name="ssg-debian8-ocil.xml" uri="#scap_org.open-scap_cref_ssg-debian8-ocil.xml"/></cat:catalog></ds:component-ref></ds:checklists><ds:checks><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-oval.xml" xlink:href="#scap_org.open-scap_comp_ssg-debian8-oval.xml"/></ds:checks><ds:extended-components><ds:component-ref id="scap_org.open-scap_cref_ssg-debian8-ocil.xml" xlink:href="#scap_org.open-scap_ecomp_ssg-debian8-ocil.xml"/></ds:extended-components></ds:data-stream><ds:component id="scap_org.open-scap_comp_ssg-debian8-oval.xml" timestamp="2017-02-23T16:42:55"><oval_definitions xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:linux="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux" xmlns:unix="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix" xmlns:ind="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5 oval-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#independent independent-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#unix unix-definitions-schema.xsd         http://oval.mitre.org/XMLSchema/oval-definitions-5#linux linux-definitions-schema.xsd">
              <check-content-ref name="ocil:ssg-file_permissions_systemmap_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_shadow_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_gshadow_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
              <check-content-ref name="ocil:ssg-file_permissions_etc_passwd_ocil:questionnaire:1" href="ssg-debian8-ocil.xml"/>
```

**Comment by pthierry38** [comment]
In the previous version, the ds data-stream-collection is shorter and doesn't contain the ocil file:

```xml
<ds:data-stream-collection xmlns:ds="http://scap.nist.gov/schema/scap/source/1.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cat="urn:oasis:names:tc:entity:xmlns:xml:catalog" id="scap_org.open-scap_collection_from_xccdf_ssg-debian8-xccdf-1.2.xml" schematron-version="1.2">
  <ds:data-stream id="scap_org.open-scap_datastream_from_xccdf_ssg-debian8-xccdf-1.2.xml" scap-version="1.2" use-case="OTHER">
    <ds:dictionaries>
      <ds:component-ref id="scap_org.open-scap_cref_output--ssg-debian8-cpe-dictionary.xml" xlink:href="#scap_org.open-scap_comp_output--ssg-debian8-cpe-dictionary.xml">
        <cat:catalog>
```

Same for Chromium.

**Comment by redhatrises** [comment]
Is this because the OpenSCAP version is 1.2.8 vs 1.2.10?

**Comment by mpreisler** [comment]
> It may be an invalid href usage in the generated xccdf file (end of each line):

I don't see anything wrong with the code, can you elaborate?

**Comment by mpreisler** [comment]
> Is this because the OpenSCAP version is 1.2.8 vs 1.2.10?

That is pretty unlikely.

The extended-components warning is harmless, it's a workaround for a bug in old OpenSCAP. If it does nothing that's completely fine.

**Comment by mpreisler** [comment]
> Is this because the OpenSCAP version is 1.2.8 vs 1.2.10?
> That is pretty unlikely.

I did some testing and I can't see anything wrong with the OCIL files. So it could be openscap failing to add them to the datastream.

**Comment by mpreisler** [comment]
The OCIL add failure happens even with the old build system and it doesn't break the datastream.

**Comment by redhatrises** [comment]
> The OCIL add failure happens even with the old build system and it doesn't break the datastream.

Which is the nice thing about the new one. We know sooner if there is a problem with the build components/content.

**Comment by pthierry38** [comment]
Sorry to come back so late, I had to get back my son at school.
I've tested with the last oscap version on the same host:
```
$ oscap --version
OpenSCAP command line tool (oscap) 1.2.14
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/local/share/openscap/schemas
Default CPE files: /usr/local/share/openscap/cpe
Probes: /usr/local/libexec/openscap

==== Inbuilt CPE names ====

==== Supported OVAL objects and associated OpenSCAP probes ====
OVAL family   OVAL object                  OpenSCAP probe              
----------    ----------                   ----------                  
(null)        system_info                  probe_system_info           
independent   family                       probe_family                
independent   filehash                     probe_filehash              
independent   environmentvariable          probe_environmentvariable   
independent   textfilecontent54            probe_textfilecontent54     
independent   textfilecontent              probe_textfilecontent       
independent   variable                     probe_variable              
independent   xmlfilecontent               probe_xmlfilecontent        
independent   environmentvariable58        probe_environmentvariable58 
independent   filehash58                   probe_filehash58            
linux         dpkginfo                     probe_dpkginfo              
linux         inetlisteningservers         probe_inetlisteningservers  
linux         rpminfo                      probe_rpminfo               
linux         partition                    probe_partition             
linux         iflisteners                  probe_iflisteners           
linux         rpmverify                    probe_rpmverify             
linux         rpmverifyfile                probe_rpmverifyfile         
linux         rpmverifypackage             probe_rpmverifypackage      
linux         selinuxboolean               probe_selinuxboolean        
linux         selinuxsecuritycontext       probe_selinuxsecuritycontext
linux         systemdunitproperty          probe_systemdunitproperty   
linux         systemdunitdependency        probe_systemdunitdependency 
unix          file                         probe_file                  
unix          interface                    probe_interface             
unix          password                     probe_password              
unix          process                      probe_process               
unix          runlevel                     probe_runlevel              
unix          shadow                       probe_shadow                
unix          uname                        probe_uname                 
unix          xinetd                       probe_xinetd                
unix          sysctl                       probe_sysctl                
unix          process58                    probe_process58             
unix          fileextendedattribute        probe_fileextendedattribute 
unix          routingtable                 probe_routingtable          
unix          symlink                      probe_symlink
```
The build seems to work (chomium done, fedora done, rhel6 done, no building rhel7...)
It seems that the Ubuntu Xenial version of OpenSCAP (1.2.8) doesn't support the newly generated files, but I don't know why.

**Comment by mpreisler** [comment]
@pthierry38 A think a solution would be to figure out which version fixes this and check for it at configure time. If we are on an openscap that is known to have this issue we would silence the OCIL add failure. It's better not to have the OCIL in the datastream than to fail the build. If we have a proper warning at configure time I think that would be a good compromise.

**Comment by pthierry38** [comment]
@mpreisler Ok I'll check OpenSCAP versions between 1.2.8 and 1.2.14 to check from which version it works.

**Comment by pthierry38** [comment]
@mpreisler I've built SSG (same commit) with oscap 1.2.9 and it works. What is "strange" is that the ds:data-stream-collection doesn't contain the ssg-debian8-ocil.xml. Looks like the oscap 1.2.9 properly deactivate the OCIL integration in the DS:
```xml
<?xml version="1.0"?>
<ds:data-stream-collection xmlns:ds="http://scap.nist.gov/schema/scap/source/1.2" xmlns:cat="urn:oasis:names:tc:entity:xmlns:xml:catalog" xmlns:xlink="http://www.w3.org/1999/xlink" id="scap_org.open-scap_collection_from_xccdf_ssg-debian8-xccdf-1.2.xml" schematron-version="1.2">
  <ds:data-stream id="scap_org.open-scap_datastream_from_xccdf_ssg-debian8-xccdf-1.2.xml" scap-version="1.2" use-case="OTHER">
    <ds:dictionaries>
      <ds:component-ref id="scap_org.open-scap_cref_--home--pret--git--scap--scap-security-guide--build--ssg-debian8-cpe-dictionary.xml" xlink:href="#scap_org.open-scap_comp_--home--pret--git--scap--scap-security-guide--build--ssg-debian8-cpe-dictionary.xml">
        <cat:catalog>
          <cat:uri name="ssg-debian8-cpe-oval.xml" uri="#scap_org.open-scap_cref_--home--pret--git--scap--scap-security-guide--build--ssg-debian8-cpe-oval.xml"/>
        </cat:catalog>
      </ds:component-ref>
    </ds:dictionaries>
```
I didn't specify any configure time options (other than prefix). I wondered if the libopenscap8 package of Ubuntu (and probably Debian) is properly configured but after a reviewing the configure is called as bellow:
```shell
./configure --enable-perl PYTHON=/usr/bin/python${PYVERSION}
```
Maybe OpenSCAP 1.2.8 and previous doesn't support OCIL integration in DS headers, and 1.2.9 support deactivation at DS build time to avoid error ?

**Comment by yuumasato** [comment]
Hi, @pthierry38  we are preparing for a release. 
Do you think you can fix this  until March, 14th? Or should we postpone this to next release?

**Comment by pthierry38** [comment]
Hi, @yuumasato I don't think I will have enough time to fix it for this release. I propose to postpone it. I will work on the patch. If I manage to make it work before the deadline I will set the patch as a Debian quilt patch for the scap-security-guide package, waiting for the next release to go upstream.

**Comment by redhatrises** [comment]
@pthierry38 have you been able to look at this at all?

**Comment by redhatrises** [comment]
Closing. This is building according to the Travis CI builds. See https://travis-ci.org/OpenSCAP/scap-security-guide/jobs/403124394
