### ISSUE TITLE
Travis CI - Investigate CentOS Docker failures

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/scap-security-guide#3203]
I've been unable to replicate these failures locally, so I'll file a help-wanted bug.

Many of the PR builds fail in Travis CI on CentOS. They fail with one of two stack traces: 

```python
Traceback (most recent call last):
  File "/home/oscap/scap-security-guide/build-scripts/combine_ovals.py", line 104, in <module>
    main()
  File "/home/oscap/scap-security-guide/build-scripts/combine_ovals.py", line 60, in main
    args.ovaldirs)
  File "/home/oscap/scap-security-guide/ssg/build_ovals.py", line 295, in checks
    os.path.join(oval_dir, filename), env_yaml
  File "/home/oscap/scap-security-guide/ssg/jinja.py", line 89, in process_file
    template = _get_jinja_environment(substitutions_dict).get_template(filepath)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 552, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib64/python2.6/site-packages/jinja2/loaders.py", line 102, in load
    bucket = bcc.get_bucket(environment, name, filename, source)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 166, in get_bucket
    self.load_bytecode(bucket)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 234, in load_bytecode
    bucket.load_bytecode(f)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 71, in load_bytecode
    self.code = marshal.load(f)
ValueError: bad marshal data
```

Or

```python
Traceback (most recent call last):
  File "/home/oscap/scap-security-guide/build-scripts/combine_ovals.py", line 100, in <module>
    main()
  File "/home/oscap/scap-security-guide/build-scripts/combine_ovals.py", line 56, in main
    args.ovaldirs)
  File "/home/oscap/scap-security-guide/ssg/build_ovals.py", line 262, in checks
    os.path.join(oval_dir, filename), env_yaml
  File "/home/oscap/scap-security-guide/ssg/jinja.py", line 89, in process_file
    template = _get_jinja_environment(substitutions_dict).get_template(filepath)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 552, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib64/python2.6/site-packages/jinja2/loaders.py", line 102, in load
    bucket = bcc.get_bucket(environment, name, filename, source)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 166, in get_bucket
    self.load_bytecode(bucket)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 234, in load_bytecode
    bucket.load_bytecode(f)
  File "/usr/lib64/python2.6/site-packages/jinja2/bccache.py", line 71, in load_bytecode
    self.code = marshal.load(f)
EOFError: EOF read where object expected
```

We should investigate whether or not this is a Travis-only problem, whether this is some issue with CentOS + jinja2, CentOS on Docker, or some other issue.

If it is a Travis-only problem, we could report it to them and/or work around it by disabling the bytecode cache (making our builds slower). 

If it is a CentOS issue, we might need to report a bug upstream (to jinja? or CentOS depending on the source) and/or disable the bytecode cache completely (again, making our builds slower).

**Comment by cipherboy** [comment]
It looks like this has been resolved after messaging Travis Support. Closing. :)
