### ISSUE TITLE
OVAL for RHEL7 service_firewalld_enabled

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#697]

**Comment by redhatrises** [comment]
Looks like this already exists. Closing.

**Comment by shawndwells** [comment]
Comes back as "notchecked" when running a scan. 

Looks like the build system isn't pulling in the appropriate OVAL check dependencies 

`````
$ ./testcheck.py oval_5.11/service_firewalld_enabled.xml 
Traceback (most recent call last):
  File "./testcheck.py", line 11, in <module>
    testcheck_module.main()
  File "../../../../shared/modules/testcheck_module.py", line 154, in main
    defname = add_oval_elements(body)
  File "../../../../shared/modules/testcheck_module.py", line 73, in add_oval_elements
    includedbody = read_ovaldefgroup_file(defid+".xml")
  File "../../../../shared/modules/testcheck_module.py", line 115, in read_ovaldefgroup_file
    with open(testfile, 'r') as test_file:
IOError: [Errno 2] No such file or directory: 'package_firewalld_installed.xml'
`````

**Comment by redhatrises** [comment]
@shawndwells Just did a scan running the following:
```
cd RHEL/7
make
cd output
oscap xccdf eval --profile ospp-rhel7-server --report /tmp/results.html --cpe ssg-rhel7-cpe-dictionary.xml ssg-rhel7-xccdf.xml
```
and the `Verify firewalld Enabled` check passed which is the `service_firewalld_enabled.xml` check.

> `````
$ ./testcheck.py oval_5.11/service_firewalld_enabled.xml 
Traceback (most recent call last):
  File "./testcheck.py", line 11, in <module>
    testcheck_module.main()
  File "../../../../shared/modules/testcheck_module.py", line 154, in main
    defname = add_oval_elements(body)
  File "../../../../shared/modules/testcheck_module.py", line 73, in add_oval_elements
    includedbody = read_ovaldefgroup_file(defid+".xml")
  File "../../../../shared/modules/testcheck_module.py", line 115, in read_ovaldefgroup_file
    with open(testfile, 'r') as test_file:
IOError: [Errno 2] No such file or directory: 'package_firewalld_installed.xml'
`````

This is expected to fail because the `package_firewalld_installed.xml` resides under `shared/oval` instead of `oval_5.11`.

**Comment by iankko** [comment]
@shawndwells 
> Comes back as "notchecked" when running a scan.

Two issues here:
* Are you sure you have openscap >= 1.2.4 installed on the system where the SSG content is build? SSG is instructed when oscap on the underlying system doesn't support OVAL-5.11 yet, not to include the service / systemd checks into the XCCDF. So if the content was built with oscap <= 1.2.5, ```notchecked``` is expected output.

> Looks like the build system isn't pulling in the appropriate OVAL check dependencies
```
$ ./testcheck.py oval_5.11/service_firewalld_enabled.xml 
Traceback (most recent call last):
  File "./testcheck.py", line 11, in <module>
    testcheck_module.main()
  File "../../../../shared/modules/testcheck_module.py", line 154, in main
    defname = add_oval_elements(body)
  File "../../../../shared/modules/testcheck_module.py", line 73, in add_oval_elements
    includedbody = read_ovaldefgroup_file(defid+".xml")
  File "../../../../shared/modules/testcheck_module.py", line 115, in read_ovaldefgroup_file
    with open(testfile, 'r') as test_file:
IOError: [Errno 2] No such file or directory: 'package_firewalld_installed.xml'
```

* Tracked this under: https://github.com/OpenSCAP/scap-security-guide/issues/765 (so it's not forgotten)

**Comment by shawndwells** [comment]
On 9/29/15 12:59 PM, iankko wrote:
>
> Two issues here:
>
>   * Are you sure you have openscap >= 1.2.4 installed on the system
>     where the SSG content is build? SSG is instructed when oscap on
>     the underlying system doesn't support OVAL-5.11 yet, not to
>     include the service / systemd checks into the XCCDF. So if the
>     content was built with oscap <= 1.2.5, |notchecked| is expected
>     output.
>
I'm hitting this. Using oscap 1.1.1 on RHEL7.
